name: 🔥 RAI CONFIG BOT

on:
  schedule:
    - cron: "0 */6 * * *"
    - cron: "30 */6 * * *"
  workflow_dispatch:
  push:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pytelegrambotapi
      - name: Run Bot
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OWNER: ${{ secrets.OWNER_ID }}
        run: python bot.py
